# Use official Node base image
FROM node:20-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy rest of the code
COPY . .

# Expose port (adjust based on your server)
EXPOSE 5000

# Start app
CMD ["npm", "start"]
